import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import axios from 'axios';
import styles from '../../styles/Home.module.css';

export default function Postview(props) {
  const router = useRouter();

  const [postId, setPostId] = useState('');
  const [post, setPost] = useState({});

  useEffect(() => {
    if (!router.isReady) {
      return;
    }
    setPostId(router.query.post_id);
  }, [router.isReady]);

  const getPost = (id) => {
    axios.get(`/api/get_post/${id}`).then((res) => {
      setPost(res.data);
    });
  };

  useEffect(() => {
    if (postId === '') {
      return;
    }
    getPost(postId);
  }, [postId]);

  return (
    <div className={styles.container}>
      <Head>
        <title>投稿一覧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <h1>投稿一覧</h1>

          {post !== {} && (
            <div>
              <h1>{post.author}</h1>
              <div>
                {post.lat} / {post.lng}
              </div>
              <div>{post.publish_at}</div>
              {post.context}
              <div>
                <img src={post.image_url} alt="投稿画像" />
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
