import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Postview(props) {
  const [posts, setPosts] = useState([]);

  const getPosts = () => {
    axios.get("/api/get_posts").then((res) => {
      setPosts(res.data["posts"]);
    });
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>投稿一覧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="border-gray-700 border-2">
          <h1 className="mt-10 flex flex-row justify-center text-4xl font-bold">
            投稿一覧
          </h1>

          <ul>
            {posts.map((post) => (
              <li key={post.id}>
                <h2 className="mt-10 text-4xl font-bold">{post.author}</h2>
                {/* <div>
                  {post.lat} / {post.lng}
                </div> */}
                <div>{post.publish_at}</div>
                {post.context}
                <div>
                  <img
                    src={post.image_url}
                    alt="投稿画像"
                    width={380}
                    height={380}
                  />
                </div>

                {post.id}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
}
