import { PRERENDER_REVALIDATE_ONLY_GENERATED_HEADER } from 'next/dist/server/api-utils';
import Head from 'next/head';
import Image from 'next/image';
import { PrismaClient } from '@prisma/client';
import styles from '../styles/Home.module.css';
import utilStyles from '../styles/utils.module.css';

export async function getServerSideProps() {
  const prisma = new PrismaClient();
  const result = await prisma.post.findMany();
  return {
    props: {
      sentence1: result[0].sentence,
      sentence2: result[1].sentence,
      sentence4: result[3].sentence,
    },
  };
}

export default function Db(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>投稿一覧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href="/posts/first-post" className={styles.card}>
            <div className={styles.nav}>
              <div className={styles.profile2}>
                <Image
                  priority
                  src="/images/profile2.png"
                  className={utilStyles.borderCircle}
                  height={50}
                  width={50}
                />
              </div>
              <h2>鳥羽　太郎</h2>
              <p>{props.sentence1} </p>
            </div>

            <div className={utilStyles.border}>
              <div className={styles.div}>
                <Image
                  src="/images/image1.jpg"
                  className={utilStyles.imagestyle2}
                  height={144}
                  width={144}
                />
                <div className={styles.risk}>
                  <Image priority src="/images/risk1.png" height={30} width={30} />
                </div>
              </div>
            </div>
          </a>

          <a href="/posts/first-post" className={styles.card}>
            <div className={styles.nav}>
              <div className={styles.profile2}>
                <Image
                  priority
                  src="/images/profile2.png"
                  className={utilStyles.borderCircle}
                  height={50}
                  width={50}
                />
              </div>
              <h2>鳥羽　次郎</h2>
              <p>木が倒れてくるかも！</p>
            </div>

            <div className={utilStyles.border}>
              <div className={styles.div}>
                <Image
                  src="/images/image2.jpg"
                  className={utilStyles.imagestyle2}
                  height={144}
                  width={144}
                />
                <div className={styles.risk}>
                  <Image priority src="/images/risk2.png" height={30} width={30} />
                </div>
              </div>
            </div>
          </a>

          <a href="/posts/first-post" className={styles.card}>
            <div className={styles.nav}>
              <div className={styles.profile2}>
                <Image
                  priority
                  src="/images/profile2.png"
                  className={utilStyles.borderCircle}
                  height={50}
                  width={50}
                />
              </div>
              <h2>鳥羽　三郎</h2>
              <p>{props.sentence4}</p>
            </div>

            <div className={utilStyles.border}>
              <div className={styles.div}>
                <Image
                  src="/images/image6.jpg"
                  className={utilStyles.imagestyle2}
                  height={144}
                  width={144}
                />
                <div className={styles.risk}>
                  <Image priority src="/images/risk3.png" height={30} width={30} />
                </div>
              </div>
            </div>
          </a>

          <a href="/posts/first-post" className={styles.card}>
            <div className={styles.nav}>
              <div className={styles.profile2}>
                <Image
                  priority
                  src="/images/profile2.png"
                  className={utilStyles.borderCircle}
                  height={50}
                  width={50}
                />
              </div>
              <h2>鳥羽　五郎</h2>
              <p>道が狭くて危ない！</p>
            </div>

            <div className={utilStyles.border}>
              <div className={styles.div}>
                <Image
                  src="/images/image4.jpg"
                  className={utilStyles.imagestyle2}
                  height={144}
                  width={144}
                />
                <div className={styles.risk}>
                  <Image priority src="/images/risk2.png" height={30} width={30} />
                </div>
              </div>
            </div>
          </a>

          <a href="/posts/first-post" className={styles.card}>
            <div className={styles.nav}>
              <div className={styles.profile2}>
                <Image
                  priority
                  src="/images/profile2.png"
                  className={utilStyles.borderCircle}
                  height={50}
                  width={50}
                />
              </div>
              <h2>鳥羽　五郎</h2>
              <p>洪水がおきるかも！</p>
            </div>

            <div className={utilStyles.border}>
              <div className={styles.div}>
                <Image
                  src="/images/image5.jpg"
                  className={utilStyles.imagestyle2}
                  height={144}
                  width={144}
                />
                <div className={styles.risk}>
                  <Image priority src="/images/risk1.png" height={30} width={30} />
                </div>
              </div>
            </div>
          </a>
        </div>
      </main>
    </div>
  );
}
