import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import axios from "axios";
import dayjs from "dayjs";
import Image from "next/image";

export default function Postview(props) {
  const [posts, setPosts] = useState([]);

  const getPosts = () => {
    axios.get("/api/get_posts").then((res) => {
      setPosts(res.data["posts"]);
    });
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div className="justfy-center">
      <Head>
        <title>投稿一覧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {/* <Link href="/">
            <a>私も投稿したいなぁ！</a>
          </Link>
          <Link href="/map">
            <a>マップ</a>
          </Link> */}
          <div className="flex flex-col">
            <div className="mt-10 flex flex-row justify-center">
              <div>
                {/* pngをアイコンにする */}
                <Image src="/image/postview.png" width={43} height={43} />
              </div>
              <h1 className="text-4xl font-bold flex justify-items-center">
                投稿一覧
              </h1>
            </div>
            <div className="w-240 h-240flex flex-col justify-center">
              <ul>
                {posts.map((post) => (
                  <li key={post.id}>
                    {/* <div className="flex flex-row"> */}
                    <div className="m-10 p-10 w-120 h-120 flex flex-col items-center border-gray-700 border-2 rounded-xl">
                      <div>
                        <img
                          className="border-1 rounded-xl"
                          src={post.image_url}
                          alt="投稿画像"
                          width={400}
                          height={400}
                        />
                      </div>

                      <p className="m-5 text-left text-xl font-bold">
                        {post.author}
                      </p>
                      {/* <div>
                  {post.lat} / {post.lng}
                </div> */}
                      <p className="text-lg">{post.context}</p>

                      {/* {post.id} */}
                      <div className="text-right">
                        {dayjs(post.publish_at).format(
                          "MM月DD日HH時mm分に投稿されました"
                        )}
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
